@startuml
title クラス図

abstract class ユーザー {
    + プロフィール
}
ユーザー -* プロフィール

class プロフィール {
    + 名前
    + メールアドレス
}

class 会員 {
    + 会員番号
}

class 管理者 {
    + ロール
}

ユーザー <|-- 管理者
ユーザー <|-- 会員

@enduml